---
version: '3'

set:
  - errexit
  - nounset
  - pipefail

vars:
  DEBIAN_VERSION: 12.5
  TINI_VERSION: 0.19.0

  IMAGE_REPOSITORY: ghcr.io/m18unet/docker-ansible-debian12
  IMAGE_TAG: latest
  IMAGE_NAME: "{{ .IMAGE_REPOSITORY }}:{{ .IMAGE_TAG }}"

tasks:
  build:
    silent: true
    cmd: |-
      docker build \
        --tag {{ .IMAGE_NAME }} \
        --build-arg DEBIAN_VERSION={{ .DEBIAN_VERSION }} \
        --build-arg TINI_VERSION={{ .TINI_VERSION }} \
        --progress plain \
        .

  run:
    silent: true
    deps:
      - build
    cmd: docker run --rm -it {{ .IMAGE_NAME }}

  login:
    silent: true
    cmd: cat pat | docker login ghcr.io -u m18unet --password-stdin

  push:
    deps:
      - login
    silent: true
    cmd: docker push {{ .IMAGE_NAME }}
